config/routes.rb
Rails.application.routes.draw do
  get 'goals/resources'

  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/contact' => 'welcome#contact'

  resources :goals do
    resources :weeks do
      resources :activities
    end
  end

  resources :biometrics
  resources :infos

  put '/update_activity' => 'activities#update'
  get '/activity_tr' => 'activities#activity_tr'
  get '/calendar' => 'activities#display'
  get '/plan_of_action/:goal_id'  => 'weeks#plan_of_action', as: :plan_of_action
  post '/create_plan/:goal_id/' => 'weeks#create_plan', as: :create_plan
  get '/bank' => 'activities#bank'

  get '/search_results' => 'welcome#search', as: :search_results
  get '/progress' => 'activities#progress'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :week, dependent: :destroy
  self.inheritance_column = :type

   def icon

   end

   def title
     self.type != "Custom" ? "#{self.type} for #{self.duration} minutes: '#{self.description}'" :  "#{self.name} for #{self.duration} minutes: '#{self.description}'"
   end

   def self.types
     %w(Running Biking Swimming Hiking Custom DogWalking Yoga Gym Skiing)
   end

   def self.mon
     where(day_of_week: 'mon' )
   end

   def self.tues
     where(day_of_week: 'tue')
   end

   def self.wed
     where(day_of_week: 'wed')
     #returns all activities that are logged on wed
   end

   def self.thurs
     where(day_of_week: 'thu' )
   end

   def self.fri
     where(day_of_week: 'fri' )
   end

   def self.sat
     where(day_of_week: 'sat' )
   end

   def self.sun
     where(day_of_week: 'sun' )
   end

   def self.complete
     where(complete: true)
   end

   def self.not_complete
     where.not(complete: true)
   end

end

app/models/biking.rb
class Biking < Activity

  def icon
    return "fa fa-bicycle fa-3x"
  end


end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :weight

  def self.sort_by_created_at
    order(:created_at)
  end

  # def self.create_arrays(biometrics, current_user)
  #   @bio_array = [['date', 'weight'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     bioweight = bio.weight
  #     @bio_array << [biodate, bioweight]
  #   end

  #   @bmi_array = [['date', 'bmi'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     biobmi = bio.weight * 703 / current_user.info.height ** 2
  #     @bmi_array << [biodate, biobmi]
  #   end

    # @speed_array = [['date', 'speed'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end

    # @strength_array = [['date', 'strength'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end
  # end

end

app/models/custom.rb
class Custom < Activity

  def icon
    return "fa fa-heartbeat fa-3x"
  end

end

app/models/dog_walking.rb
class DogWalking < Activity

  def icon
    return "fi-guide-dog large-icon"
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :weeks

  validates_presence_of :time_frame
end

app/models/gym.rb
class Gym < Activity

  def icon
    return "gym"
  end

end

app/models/hiking.rb
class Hiking < Activity

  def icon
    return "fi-mountains large-icon"
  end


end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :height
end

app/models/running.rb
class Running < Activity

  def icon
    return "fi-foot large-icon"
  end

end

app/models/skiing.rb
class Skiing < Activity

  def icon
    return "skiing"
  end

end

app/models/swimming.rb
class Swimming < Activity

  def icon
    return "swimming"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :goals
  has_many :biometrics, dependent: :destroy
  has_one :info, dependent: :destroy

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.signup_email(self).deliver_now
  end

end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :goal, dependent: :destroy
  has_many :activities

 #do we need this?
  # def is_complete?
  #   self.activities_complete.length == self.activities.length
  # end
  
end

app/models/yoga.rb
class Yoga < Activity

  def icon
    return "yoga"
  end

end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :find_user
  before_action :find_week, only: [:show, :update]
  before_action :find_goal

  def index
    @weeks = @goal.weeks

  end

  def show
    @activities = @week.activities
  end

  def edit
    @week = Week.find_by(id: params[:id])
  end

  def update
    if @week.update(week_params)
      redirect_to (goal_week_path(@goal.id, @week.id))
    end
  end

  def plan_of_action
    @weeks = @goal.weeks

    activities = @goal.weeks.first.activities
    @activities = activities.map do |activity|
        activity.type
    end
    @activities.uniq!
  end

  def create_plan
    per_week = params[:week][:per_week].to_i
    @goal.weeks.each do |week|
      per_week.times do
        activity = week.activities.new(type: params[:week][:type], name: params[:week][:name])
        activity.save
      end
    end
    redirect_to plan_of_action_path(@goal.id)
  end

  private

  def find_user
    @user = current_user
  end


  def find_goal
    @goal = Goal.find_by(id: params[:goal_id])
  end

  def week_params
    params.fetch(:week, {}).permit(:name, :activities)
  end

  def find_week
    @week = Week.find_by(id: params[:id])
    unless @week
      render(text: 'Week not found', status: 404)
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
	# Returns a dynamic path based on the provided parameters
	def sti_activity_path(type = "activity", activity = nil, action = nil)
	  send "#{format_sti(action, type, activity)}_path", activity
	end

	def format_sti(action, type, activity)
	  action || activity ?
	  "#{format_action(action)}#{type.underscore}" :
	  "#{type.underscore.pluralize}"
	end

	def format_action(action)
	  action ? "#{action}_" : ""
	end
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/weeks/edit.html.erb
<h2>weeks edit for testing purposes</h2>
<h2>delete this and show aciton if not needed</h2>

app/views/weeks/index.html.erb
<div class="row">
  <div class="col-sm-12 text-center">
    <h2><%= @goal.description %></h2>
    <hr>
    <div id="carousel-example-generic" class="text-center carousel slide data-interval= "false"" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @weeks.count.times do |num|%>
          <li data-target="#carousel-example-generic"data-slide-to="<%= num.to_s %>"class="<%= num.zero? ? 'active' : '' %>"></li>
        <% end %>
      </ol>

      <!-- Wrapper for slides -->
      <a class="left" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

       <a class="right" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      <div class="carousel-inner" role="listbox">
        <% @weeks.each_with_index do |week, index| %>
          <div id="carousel-week" data-index-id="<%= index %>" class="item week-item-container text-center <%= index.zero? ? 'active' : '' %>">
            <% activities_complete = week.activities.complete %>
            <% activities_not_complete = week.activities.not_complete %>
            <%= render partial: "activities/activities_display", locals: {activities_not_complete: activities_not_complete, activities_complete: activities_complete, week: week, index: index} %>

            <%= link_to goal_week_activities_path(week.goal_id, week.id), class: 'week-item-link' do %>
            <% end %>
          </div>


          <!-- Add Activity Modal -->
          <div class="container-fluid">
            <div class="modal fade" id="myModal<%= week.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Activities</h4>
                  </div>
                  <div class="modal-body">
                    <%= render "activities/new", locals: {week_id: week.id} %>
                  </div>
                  <div class="modal-footer">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

        <!-- Log Modal -->
        <div class="container-fluid">
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Log Activities</h4>
                </div>
                <div class="modal-body">
                  <div id="activities-holder">

                  </div>
                  <button type="button" id="log-activities-button" class="btn btn-default">Submit Log</button>
                </div>
                <div class="modal-footer">
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Controls -->

      </div>

    </div>
  </div>
</div>

app/views/weeks/plan_of_action.html.erb
<div class="col-sm-12 text-center">
<h2>How are you going to obtain this goal?</h2>
<hr>
<h3>Lets add some activities to help you achieve your goal </h3>

<%= form_for :week,  url: create_plan_path(@goal.id) do |f| %>

<h5>First Choose a type of activity that you would like to do during the week</h5>
  <div class="form-group">
    <%=  f.label('Type') %>
    <br>
    <%= f.select :type, Activity.types %>
    <div style='display: none' id="custom-activity-text">
      <%=  f.label('Name') %><br>
      <%= f.text_field :name %>
    </div>
  </div>

<h5>Then choose how many times you want to do this activity per week</h5>
  <div class="form-group">
    <%=  f.label('Times Per Week') %>
    <br>
    <%= f.select :per_week, (1..7).to_a %>
  </div>

  <h5>Continue to add activities until you are satisfied </h5>
  <button type="submit" class="btn btn-default">Add Activity</button>
  <h5>When you all done, click "Finish"</h5>

<% end %>

<% @activities.each do |activity|%>
  <p>
    You have added <%= activity %>
  </p>
<% end %>
<br>
<br>
<br>
<br>
<%= link_to 'Finish', goal_weeks_path(@goal.id), class: "act-button btn btn-default btn-lg"  %>
</div>

app/views/weeks/show.html.erb
<h2>weeks show for testing purposes</h2>
<h2>delete this and show aciton if not needed</h2>