config/routes.rb
Rails.application.routes.draw do
  get 'goals/resources'

  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/contact' => 'welcome#contact'

  resources :goals do
    resources :weeks do
      resources :activities
    end
  end

  resources :biometrics
  resources :infos

  put '/update_activity' => 'activities#update'
  get '/activity_tr' => 'activities#activity_tr'
  get '/calendar' => 'activities#display'
  get '/plan_of_action/:goal_id'  => 'weeks#plan_of_action', as: :plan_of_action
  post '/create_plan/:goal_id/' => 'weeks#create_plan', as: :create_plan
  get '/bank' => 'activities#bank'

  get '/search_results' => 'welcome#search', as: :search_results
  get '/progress' => 'activities#progress'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :week, dependent: :destroy
  self.inheritance_column = :type

   def icon

   end

   def title
     self.type != "Custom" ? "#{self.type} for #{self.duration} minutes: '#{self.description}'" :  "#{self.name} for #{self.duration} minutes: '#{self.description}'"
   end

   def self.types
     %w(Running Biking Swimming Hiking Custom DogWalking Yoga Gym Skiing)
   end

   def self.mon
     where(day_of_week: 'mon' )
   end

   def self.tues
     where(day_of_week: 'tue')
   end

   def self.wed
     where(day_of_week: 'wed')
     #returns all activities that are logged on wed
   end

   def self.thurs
     where(day_of_week: 'thu' )
   end

   def self.fri
     where(day_of_week: 'fri' )
   end

   def self.sat
     where(day_of_week: 'sat' )
   end

   def self.sun
     where(day_of_week: 'sun' )
   end

   def self.complete
     where(complete: true)
   end

   def self.not_complete
     where.not(complete: true)
   end

end

app/models/biking.rb
class Biking < Activity

  def icon
    return "fa fa-bicycle fa-3x"
  end


end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :weight

  def self.sort_by_created_at
    order(:created_at)
  end

  # def self.create_arrays(biometrics, current_user)
  #   @bio_array = [['date', 'weight'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     bioweight = bio.weight
  #     @bio_array << [biodate, bioweight]
  #   end

  #   @bmi_array = [['date', 'bmi'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     biobmi = bio.weight * 703 / current_user.info.height ** 2
  #     @bmi_array << [biodate, biobmi]
  #   end

    # @speed_array = [['date', 'speed'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end

    # @strength_array = [['date', 'strength'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end
  # end

end

app/models/custom.rb
class Custom < Activity

  def icon
    return "fa fa-heartbeat fa-3x"
  end

end

app/models/dog_walking.rb
class DogWalking < Activity

  def icon
    return "fi-guide-dog large-icon"
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :weeks

  validates_presence_of :time_frame
end

app/models/gym.rb
class Gym < Activity

  def icon
    return "gym"
  end

end

app/models/hiking.rb
class Hiking < Activity

  def icon
    return "fi-mountains large-icon"
  end


end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :height
end

app/models/running.rb
class Running < Activity

  def icon
    return "fi-foot large-icon"
  end

end

app/models/skiing.rb
class Skiing < Activity

  def icon
    return "skiing"
  end

end

app/models/swimming.rb
class Swimming < Activity

  def icon
    return "swimming"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :goals
  has_many :biometrics, dependent: :destroy
  has_one :info, dependent: :destroy

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.signup_email(self).deliver_now
  end

end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :goal, dependent: :destroy
  has_many :activities

 #do we need this?
  # def is_complete?
  #   self.activities_complete.length == self.activities.length
  # end
  
end

app/models/yoga.rb
class Yoga < Activity

  def icon
    return "yoga"
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/new_user_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for joining SLCfit, <%= @user.username %>!</h1>
    <p>We are excited to help you acheive your goals! Now signin and get moving!</p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Favicon -->
    <%= favicon_link_tag "favicon.ico" %>
    <!-- <link rel="shortcut icon" href="assets/favicon.ico"/>
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" /> -->
    <title>SLCfit</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application'%>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.0.2/jquery.simpleWeather.min.js"></script>
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Poiret+One|Pacifico|Raleway:400,100,200,300,500,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
  </head>
  <body>
  <div id="wrapper">
    <div class="container-fluid header">
      <header class="header">
        <% if user_signed_in? %>
            <%= render(partial: 'shared/side_nav') %>
            <marquee id="weather" class="col-sm-2 banner text-center" style="margin-left: 2.5%"></marquee>
            <div id="weather" class="pull-right col-sm-2"></div>
<!--             <%#= render(partial: 'shared/flash') %>
 -->        <% end %>
      </header>
    </div>
    <div id="page-content-wrapper">
     <div class="container-fluid bg-img-width">
       <%= yield %>
     </div>
  </div>


    <script type="text/javascript">
    $(document).ready(function() {
      $.simpleWeather({
        location: 'Salt Lake City, UT',
        woeid: '',
        unit: 'f',
        success: function(weather) {
          html = '<p><i class="icon-'+weather.code+'"></i> '+weather.temp+'&deg;'+weather.units.temp + '&nbsp&nbsp&nbsp&nbsp';
          html += weather.title + '</p>';
          $("#weather").html(html);
        },
        error: function(error) {
          $("#weather").html('<p>'+error+'</p>');
        }
      });
    });
    </script>
    </div>
    <div class="footer-main">
      <p>&copy<%= Time.now.year %></p>
    </div>
 </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SLCfit</title>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application'%>
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Poiret+One|Pacifico|Raleway:400,100,200,300,500,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- google fonts -->
    <link href='http://fonts.googleapis.com/css?family=Poiret+One|Pacifico|Raleway:400,100,200,300,500,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
  </head>
  <body class='front-page-top'>
    <div class="container-fluid header-splash">
      <header class="header-splash">
        <%= render(partial: 'shared/top_nav') %>
      </header>
    </div>
     <div class="container-fluid bg-img-width">
       <%= yield %>
     </div>
 </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/shared/_side_nav.html.erb
<!-- Sidebar -->
<a href="#menu-toggle" class="btn btn-default hidden-lg hidden-md side-nav-button" id="menu-toggle"><i class="fa fa-bars"></i></a>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <h1><%= link_to 'SLCfit', main_app.goals_path %></h1>
    </li>
    <li>
      <!-- <p><%#= image_tag current_user.image(:thumb), class: "profile-pic" %></p> -->
      <h3 class='side-nav-username'><%= current_user.username %></h3>
    </li>
    <li><%= link_to 'My Goals', main_app.goals_path %></li>
    <li>
      <li><%= link_to 'My Biometrics', main_app.biometrics_path %></li>
    
    <!-- <li><%#= link_to 'New Info', main_app.new_info_path %></li> -->
    </li>
    <li><%= link_to 'Account Settings', main_app.edit_user_registration_path %></li>
    <li><%= form_tag main_app.search_results_path, :method => 'get' do %>
      <div class="form-group" style="margin: 0 30px">
        <%= text_field_tag :term, params[:term], required: true, placeholder: 'ex: gyms', class: "form-control" %>
        <%= text_field_tag :location, params[:location], required: true, placeholder: 'City, Zip, or State', class: "form-control" %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-default"%>
        <p class="yelp">powered by <%= image_tag "https://s3-media2.fl.yelpcdn.com/assets/srv0/developer_pages/55e2efe681ed/assets/img/yelp_logo_50x25.png" %></p>
      </div>
      <% end %></li>
    <br>
    <br>
    <br>
    <li><%= link_to 'Sign Out', main_app.destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SLCfit</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#features">Features <span class="sr-only">(current)</span></a></li>
        <li><a href="#contact">Contact</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>

<!--       <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" name="username" placeholder="Username">
        </div>
        <div class="form-group">
          <input type="text" class="form-control" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Sign In</button>
      </form> -->

      <ul class="navbar-form navbar-right">
              <li>
                <%= form_for(:user, :url => session_path(:user)) do |f| %>
                <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-warning' %>
                <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
                <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
                <%= f.submit 'Sign in', class: 'btn btn-default' %>
                <%= link_to "Forgot your password?", new_password_path(:user), class: 'sr-only' %>
                <% end %>
              </li>
            </ul>
  

      
        
      
<!--         <ul class="nav navbar-nav navbar-right">
          <li><a href="<%#= new_user_registration_path %>">Sign Up</a></li>
          <li><a href="<%#= new_user_session_path %>">Login</a></li>
        </ul> -->

  


      <!-- <ul class="nav navbar-nav navbar-right"> -->
        
      
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      <!-- </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>