config/routes.rb
Rails.application.routes.draw do
  get 'goals/resources'

  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/contact' => 'welcome#contact'

  resources :goals do
    resources :weeks do
      resources :activities
    end
  end

  resources :biometrics
  resources :infos

  put '/update_activity' => 'activities#update'
  get '/activity_tr' => 'activities#activity_tr'
  get '/calendar' => 'activities#display'
  get '/plan_of_action/:goal_id'  => 'weeks#plan_of_action', as: :plan_of_action
  post '/create_plan/:goal_id/' => 'weeks#create_plan', as: :create_plan
  get '/bank' => 'activities#bank'

  get '/search_results' => 'welcome#search', as: :search_results
  get '/progress' => 'activities#progress'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :week, dependent: :destroy
  self.inheritance_column = :type

   def icon

   end

   def title
     self.type != "Custom" ? "#{self.type} for #{self.duration} minutes: '#{self.description}'" :  "#{self.name} for #{self.duration} minutes: '#{self.description}'"
   end

   def self.types
     %w(Running Biking Swimming Hiking Custom DogWalking Yoga Gym Skiing)
   end

   def self.mon
     where(day_of_week: 'mon' )
   end

   def self.tues
     where(day_of_week: 'tue')
   end

   def self.wed
     where(day_of_week: 'wed')
     #returns all activities that are logged on wed
   end

   def self.thurs
     where(day_of_week: 'thu' )
   end

   def self.fri
     where(day_of_week: 'fri' )
   end

   def self.sat
     where(day_of_week: 'sat' )
   end

   def self.sun
     where(day_of_week: 'sun' )
   end

   def self.complete
     where(complete: true)
   end

   def self.not_complete
     where.not(complete: true)
   end

end

app/models/biking.rb
class Biking < Activity

  def icon
    return "fa fa-bicycle fa-3x"
  end


end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :weight

  def self.sort_by_created_at
    order(:created_at)
  end

  # def self.create_arrays(biometrics, current_user)
  #   @bio_array = [['date', 'weight'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     bioweight = bio.weight
  #     @bio_array << [biodate, bioweight]
  #   end

  #   @bmi_array = [['date', 'bmi'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     biobmi = bio.weight * 703 / current_user.info.height ** 2
  #     @bmi_array << [biodate, biobmi]
  #   end

    # @speed_array = [['date', 'speed'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end

    # @strength_array = [['date', 'strength'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end
  # end

end

app/models/custom.rb
class Custom < Activity

  def icon
    return "fa fa-heartbeat fa-3x"
  end

end

app/models/dog_walking.rb
class DogWalking < Activity

  def icon
    return "fi-guide-dog large-icon"
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :weeks

  validates_presence_of :time_frame
end

app/models/gym.rb
class Gym < Activity

  def icon
    return "gym"
  end

end

app/models/hiking.rb
class Hiking < Activity

  def icon
    return "fi-mountains large-icon"
  end


end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :height
end

app/models/running.rb
class Running < Activity

  def icon
    return "fi-foot large-icon"
  end

end

app/models/skiing.rb
class Skiing < Activity

  def icon
    return "skiing"
  end

end

app/models/swimming.rb
class Swimming < Activity

  def icon
    return "swimming"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :goals
  has_many :biometrics, dependent: :destroy
  has_one :info, dependent: :destroy

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.signup_email(self).deliver_now
  end

end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :goal, dependent: :destroy
  has_many :activities

 #do we need this?
  # def is_complete?
  #   self.activities_complete.length == self.activities.length
  # end
  
end

app/models/yoga.rb
class Yoga < Activity

  def icon
    return "yoga"
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :find_user
  before_action :find_goal, only: [:edit, :show, :update, :create, :destroy]

  def index
    @goals = Goal.where(user_id: current_user.id)
  end

  def show
  end

  def edit
  end

  def update
    if @goal.update(goal_params)
      flash[:notice] = "Your goal was successfully updated!"
      redirect_to(goals_path)
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
        @goal.time_frame.times do
          week = @goal.weeks.new
          week.save
        end
      flash[:notice] = "Your goal was successfully created!"
      redirect_to(plan_of_action_path(@goal.id))
    end
  end

  def destroy
    @goal.destroy
    respond_to do |format|
    format.html { redirect_to goals_path, notice: 'Item was successfully destroyed.' }
    end
  end

  private

  def goal_params
    params.fetch(:goal, {}).permit(:user_id, :description, :reason, :time_frame, :complete)
  end

  def find_goal
    @goal = Goal.find_by(id: params[:id])
  end

  def find_user
    @user = current_user
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
	# Returns a dynamic path based on the provided parameters
	def sti_activity_path(type = "activity", activity = nil, action = nil)
	  send "#{format_sti(action, type, activity)}_path", activity
	end

	def format_sti(action, type, activity)
	  action || activity ?
	  "#{format_action(action)}#{type.underscore}" :
	  "#{type.underscore.pluralize}"
	end

	def format_action(action)
	  action ? "#{action}_" : ""
	end
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goals/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="text-center">
      <h2>Edit Goal</h2>
      <hr />
      <%= form_for @goal, url: goal_path(@goal.id) do |f| %>

          <div>
            <p><%= f.label("what's your goal?") %></p>
            <p><%= f.text_area :description, class: "custom-input"%></p>
          </div>

          <div class="form-group">
            <p><%= f.label('why do you want to achieve this goal?') %></p>
            <p><%= f.text_area :reason, class: "custom-input"  %></p>
          </div>

          <div class="form-group">
            <%= f.submit "Save Changes", class: "custom-submit" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- <div class="row footer">
  <p>footer</p>
</div> -->

app/views/goals/index.html.erb
<div class="row">
  <div class="col-sm-12 text-center">
    <h3><%= link_to ' ', main_app.new_goal_path, class: "fa fa-plus-circle fa-3x", data: {toggle: "tooltip", placement: "top"}, title: "new goal"%></h3>
    <h2>My Goals</h2>
    <p>these are you current goals.  click one to see your activities!</p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-12 text-center">
    <% @goals.each do |goal|  %>
      <h3>you want to <%= link_to goal.description, goal_weeks_path(goal.id) %></h3>
      <p><%= goal.reason%></p>
      <p>you have <%= goal.time_frame %> weeks to complete this goal.</p>
      <%= link_to 'Edit', edit_goal_path(goal.id) %> |
      <%= link_to 'Delete', goal_path(goal.id), method: :delete, data: {confirm: "Are you sure?"}%>
    <% end %>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<div class="container-fluid">
 <div class="row">
   <div class="text-center scroll">
     <%= form_for @goal do |f| %>
       <h2 class="page-header">New Goal</h2>

         <div>
           <h3>Whats your goal?</h3>
           <p><%= f.label('I want to...') %></p>
           <p><%= f.text_area :description, class: "custom-input"%></p>
         </div>

         <div>
           <h3>Reason</h3>
           <p><%= f.label('Why do I want to achieve this goal?') %></p>
           <p><%= f.text_area :reason, class: "custom-input" %></p>
         </div>

         <div>
           <h3>Time Frame</h3>
           <%= f.label('I will have acheived my goal in...') %>
           <%= f.select :time_frame, options_for_select(1..52), class: "form-control custom-input" %>
           <%= f.label(' weeks') %>
         </div>

         <div class="form-group">
           <%= f.submit "Create Goal", class: "custom-submit" %>
         </div>

       <% end %>
     </div>
  </div>
</div>