config/routes.rb
Rails.application.routes.draw do
  get 'goals/resources'

  get 'welcome/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/contact' => 'welcome#contact'

  resources :goals do
    resources :weeks do
      resources :activities
    end
  end

  resources :biometrics
  resources :infos

  put '/update_activity' => 'activities#update'
  get '/activity_tr' => 'activities#activity_tr'
  get '/calendar' => 'activities#display'
  get '/plan_of_action/:goal_id'  => 'weeks#plan_of_action', as: :plan_of_action
  post '/create_plan/:goal_id/' => 'weeks#create_plan', as: :create_plan
  get '/bank' => 'activities#bank'

  get '/search_results' => 'welcome#search', as: :search_results
  get '/progress' => 'activities#progress'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :week, dependent: :destroy
  self.inheritance_column = :type

   def icon

   end

   def title
     self.type != "Custom" ? "#{self.type} for #{self.duration} minutes: '#{self.description}'" :  "#{self.name} for #{self.duration} minutes: '#{self.description}'"
   end

   def self.types
     %w(Running Biking Swimming Hiking Custom DogWalking Yoga Gym Skiing)
   end

   def self.mon
     where(day_of_week: 'mon' )
   end

   def self.tues
     where(day_of_week: 'tue')
   end

   def self.wed
     where(day_of_week: 'wed')
     #returns all activities that are logged on wed
   end

   def self.thurs
     where(day_of_week: 'thu' )
   end

   def self.fri
     where(day_of_week: 'fri' )
   end

   def self.sat
     where(day_of_week: 'sat' )
   end

   def self.sun
     where(day_of_week: 'sun' )
   end

   def self.complete
     where(complete: true)
   end

   def self.not_complete
     where.not(complete: true)
   end

end

app/models/biking.rb
class Biking < Activity

  def icon
    return "fa fa-bicycle fa-3x"
  end


end

app/models/biometric.rb
class Biometric < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :weight

  def self.sort_by_created_at
    order(:created_at)
  end

  # def self.create_arrays(biometrics, current_user)
  #   @bio_array = [['date', 'weight'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     bioweight = bio.weight
  #     @bio_array << [biodate, bioweight]
  #   end

  #   @bmi_array = [['date', 'bmi'], ]

  #   biometrics.each do |bio|
  #     biodate = bio.created_at.strftime "%a %D"
  #     biobmi = bio.weight * 703 / current_user.info.height ** 2
  #     @bmi_array << [biodate, biobmi]
  #   end

    # @speed_array = [['date', 'speed'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end

    # @strength_array = [['date', 'strength'], ]

    # biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end
  # end

end

app/models/custom.rb
class Custom < Activity

  def icon
    return "fa fa-heartbeat fa-3x"
  end

end

app/models/dog_walking.rb
class DogWalking < Activity

  def icon
    return "fi-guide-dog large-icon"
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :weeks

  validates_presence_of :time_frame
end

app/models/gym.rb
class Gym < Activity

  def icon
    return "gym"
  end

end

app/models/hiking.rb
class Hiking < Activity

  def icon
    return "fi-mountains large-icon"
  end


end

app/models/info.rb
class Info < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :height
end

app/models/running.rb
class Running < Activity

  def icon
    return "fi-foot large-icon"
  end

end

app/models/skiing.rb
class Skiing < Activity

  def icon
    return "skiing"
  end

end

app/models/swimming.rb
class Swimming < Activity

  def icon
    return "swimming"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :goals
  has_many :biometrics, dependent: :destroy
  has_one :info, dependent: :destroy

  after_create :send_welcome_email

  def send_welcome_email
    UserMailer.signup_email(self).deliver_now
  end

end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :goal, dependent: :destroy
  has_many :activities

 #do we need this?
  # def is_complete?
  #   self.activities_complete.length == self.activities.length
  # end
  
end

app/models/yoga.rb
class Yoga < Activity

  def icon
    return "yoga"
  end

end

app/controllers/biometrics_controller.rb
class BiometricsController < ApplicationController
  before_action :find_user
  before_action :find_biometric, except: [:index]
  before_action :find_user
  before_action :find_info

  def index
    @biometrics = Biometric.where(user_id: current_user.id).sort_by_created_at

    unless @biometrics.count > 0
      redirect_to new_info_path
    end

     # Biometric.create_arrays(@biometrics, current_user)

    # charts = %w[weight bmi speed strength]

    # charts.map do |chart|
    #   @biometrics.each do |bio|
    #     chart_array = [['date', 'chart'], ]
    #     biodate = bio.created_at.strftime "%a %D"
    #     biochart = bio.weight

    #     chart_array << [biodate, biochart]
    #   end
    # end

    # @weight_array = =[['date', 'weight'], ]
    # biodate=bio.created_at.strftime "%a %D"
    # bioweight = bio.weight

    # @weight_array << [biodate, bioweight]


    @weight_array = [['date', 'weight'], ]

    @biometrics.each do |bio|
      biodate = bio.created_at.strftime "%a %D"
      bioweight = bio.weight
      @weight_array << [biodate, bioweight]
    end

    @bmi_array = [['date', 'bmi'], ]

    @biometrics.each do |bio|
      biodate = bio.created_at.strftime "%a %D"
      biobmi = bio.weight * 703 / current_user.info.height ** 2
      @bmi_array << [biodate, biobmi]
    end

    # @speed_array = [['date', 'speed'], ]

    # @biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end

    # @strength_array = [['date', 'strength'], ]

    # @biometrics.each do |bio|
    #   biodate = bio.created_at.strftime "%a %D"
    #   speed = bio.mile_speed
    #   @speed_array << [biodate, speed]
    # end
  end

  def show
  end

  def edit
  end

  def new
    @biometric = Biometric.new

    if @info
      string_year = current_user.info.birthday.strftime "%Y" 
      @year = string_year.to_i
    end
  end

  def create
    @biometric = current_user.biometrics.new(bio_params)
    if @biometric.save
      flash[:notice] = "your biometric for today has been saved!"
    else
      flash[:error] = "oops! you missed some data.  please try again."
    end
    redirect_to biometrics_path
  end

  def destroy
   if @biometric.destroy
   @biometric.destroy
      flash[:notice] = "Your biometric data has been destroyed."
      redirect_to biometrics_path
    else
      flash[:error] = "We couldn't destroy your data!"
    end
  end

  private

  def bio_params
    params.fetch(:biometric, {}).permit(:birthday, :age, :height, :weight, :mile_speed, :lift_weight)
  end

  def find_user
    @user = current_user
    unless @user
      redirect_to root_path
    end
  end


  def find_biometric
    @biometric = Biometric.find_by(id: params[:id])
  end

  def find_info 
    @info = Info.find_by(user_id: current_user.id)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
	# Returns a dynamic path based on the provided parameters
	def sti_activity_path(type = "activity", activity = nil, action = nil)
	  send "#{format_sti(action, type, activity)}_path", activity
	end

	def format_sti(action, type, activity)
	  action || activity ?
	  "#{format_action(action)}#{type.underscore}" :
	  "#{type.underscore.pluralize}"
	end

	def format_action(action)
	  action ? "#{action}_" : ""
	end
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/biometrics/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <div class="row side-nav">
        <%= render(partial: 'shared/side_nav') %>
      </div>
    </div>
    <div class="col-md-9 text-center">
      <h2>Edit Data</h2>
      <hr />
      <%= form_for @biometric, url: biometric_path(@biometric.id) do |f| %>
          
          <div>
            <p><%= f.label("what's your biometric?") %></p>
            <p><%= f.text_area :description, class: "custom-input"%></p>
          </div>
          
          <div class="form-group">
            <p><%= f.label('why do you want to achieve this biometric?') %></p>
            <p><%= f.text_area :reason, class: "custom-input"  %></p>
          </div>

          <div class="form-group">
            <p><%= f.label('time frame (weeks)') %></p>
            <p><%= f.select :time_frame, options_for_select(1..52), class: "custom-input"  %></p>
          </div>

          <div class="form-group">
            <%= f.submit "Save Changes", class: "custom-submit" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- <div class="row footer">
  <p>footer</p>
</div> -->

app/views/biometrics/index.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var weight_data = <%=raw @weight_array %>;
    var data = google.visualization.arrayToDataTable(weight_data);

    var options = {
      title: 'Weight Tracker',
      hAxis: {title: 'Date',  type: 'string', titleTextStyle: {color: '#333 '}},
      vAxis: {title: 'Weight', type: 'integer', minValue: 50, maxValue: 200},
      legend: {position: 'top', alignment: 'end', textStyle: {color: 'black'}},
      colors: ['purple']
      // chartArea: {width: '100%', height: '500px'}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var bmi_data = <%=raw @bmi_array %>;
    var data = google.visualization.arrayToDataTable(bmi_data);

    var options = {
      title: 'Body Mass Index Tracker',
      hAxis: {title: 'Date',  type: 'string', titleTextStyle: {color: '#333 '}},
      vAxis: {title: 'BMI', type: 'integer', minValue: 0, maxValue: 50},
      legend: {position: 'top', alignment: 'end', textStyle: {color: 'black'}},
      colors:['red']
      // chartArea: {width: '100%', height: '500px'}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('bmi_chart_div'));
    chart.draw(data, options);
  }
</script>


<div class="row">
  <div class="col-sm-12 text-center">
    <h3><%= link_to ' ', main_app.new_biometric_path, class: "fa fa-plus-circle fa-3x", data: {toggle: "tooltip", placement: "top"}, title: "new biometric"%></h3>
    <h2>My Data</h2>
    <p>track your progress!</p>
    <h3><%= flash[:error] %></h3>
    <hr>
  </div>
</div>

<% if @biometrics %>
  <div class="row">
    <div class="col-sm-12 text-center ">
      <div class="row" style="overflow: scroll">
        <div class="col-sm-6">
          <div id="chart_div" style="width: 500px; height: 500px; margin: 0 auto"></div>
        </div>
        <div class="col-sm-6">
          <div id="bmi_chart_div" style="width: 500px; height: 500px; margin: 0 auto"></div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>please create a new biometric!</p>
<% end %>
<hr>

<% @biometrics.in_groups_of(4, false).each do |group| %>
  <div class="row">
    <% group.each do |bio| %>
      <div class="col-sm-3 text-left">
        <h4>metrics for <%= bio.created_at.strftime "%a %D" %></h4>
        <hr>
        <p>weight: <%= bio.weight %>lbs.</p>
        <p>height: <%= current_user.info.height %>"</p>
        <p>body mass index: <%= (bio.weight * 703) / (current_user.info.height ** 2) %></p>
        <% if bio.mile_speed != nil %>
          <p>you can run a mile in <%= bio.mile_speed %>minutes.</p>
        <% end %>
        <% if bio.lift_weight != nil %>
          <p>you can lift <%= bio.lift_weight %>lbs.</p>
        <% end %>
        <%= link_to 'Delete', biometric_path(bio.id), method: :delete, data: {confirm: "Are you sure?"}%>
        <br>
        <br>
      </div>
    <% end %>
  </div>
<% end %>

app/views/biometrics/new.html.erb
<div class="col-md-12 text-center">
  <% if current_user.biometrics.count == 0 %>
    <%= form_for @biometric do |f| %>
      <h2>Initial Biometric Data</h2>
      <h3>this is your first data entry.</h3>
      <hr>
      <% if @info %>
        <p>You are <%= current_user.info.height %>" tall and <%= Time.now.year - @year %> years old.  
         <%= link_to 'Edit', main_app.edit_info_path(@info.id) %></p>
       <% else %>
        <h3>It seems you don't have any basic user data. Enter new data <%= link_to 'here', main_app.new_info_path %>.</h3>  
      <% end %>
      <br>
      <div>
        <h4><%= f.label('how much do you weigh?(pounds)') %></h4>
        <p><%= f.select :weight, options_for_select(70..300), class: "custom-input" %></p> 
      </div>
      <br>
      <div>
        <h4><%= f.label('how fast can you run a mile?') %></h4>
        <p><%= f.label('psst...hate running?  leave it blank!') %></p>
        <%= f.text_field :mile_speed, placeholder: "minutes", class: "custom-input" %>
      </div>
      <br>
      <div>
        <h4><%= f.label('how much can you deadlift?') %></h4>
        <p><%= f.label('hate lifting heavy things?  leave it blank!') %></p>
        <p><%= f.text_field :lift_weight, placeholder: "pounds", class: "custom-input" %> 
      </div>
      <br>
      <div class="form-group">
        <%= f.submit "save data", class: "custom-submit" %>
      </div>
    <% end %>
  <% else %>
    <%= form_for @biometric do |f| %>
      <h2>New Biometric</h2>
      <p>update your current data here!</p>
      <hr>
      <% if @info %>
        <p>You are <%= current_user.info.height %>" tall and <%= Time.now.year - @year %> years old.  
         <%= link_to 'Edit', main_app.edit_info_path(@info.id) %></p>
       <% else %>
        <h3>It seems you don't have any basic user data. Enter new data <%= link_to 'here', main_app.new_info_path %>.</h3>  
      <% end %>
      <br>
      <div>
        <h4><%= f.label('how much do you weigh?(pounds)') %></h4>
        <p><%= f.select :weight, options_for_select(70..300), class: "custom-input" %></p> 
      </div>
      <br>
      <div>
        <h4><%= f.label('how fast can you run a mile?') %></h4>
        <p><%= f.label('psst...hate running?  leave it blank!') %></p>
        <%= f.text_field :mile_speed, placeholder: "minutes", class: "custom-input" %>
      </div>
      <br>
      <div>
        <h4><%= f.label('how much can you deadlift?') %></h4>
        <p><%= f.label('hate lifting heavy things?  leave it blank!') %></p>
        <p><%= f.text_field :lift_weight, placeholder: "pounds", class: "custom-input" %> 
      </div>
      <br>
      <div class="form-group">
        <%= f.submit "create biometric", class: "custom-submit" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/biometrics/show.html.erb
<h1>Biometrics#show</h1>
<p>Find me in app/views/biometrics/show.html.erb</p>